- hosts: localhost

  vars:
  - testplugin: "{{ lookup('hashivault', 'secret=kv/data/vault token=s.fVD3uoo2PDzS9EYXgWBM2bHS url=http://192.168.122.33:8200/ validate_certs=false') }}"
  tasks:

  - name: show user
    debug:
      msg: "{{ testplugin }}"
